
package view;

import controller.ControllerItem;
import controller.ControllerShow;
import controller.ControllerVenda;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Item;



public class FrmFormularioRelatorio extends javax.swing.JInternalFrame {

    ControllerVenda controleVenda = new ControllerVenda();
    ControllerShow controleShow = new ControllerShow();
    ControllerItem controleItem = new ControllerItem();
    List<String> listaVendas = new ArrayList<String>();
    List<Item> listaItens = new ArrayList<Item>();
    
  
    
    public FrmFormularioRelatorio() {
        initComponents();
        
        listaVendas = controleVenda.carregaComboBoxVendas();
        tbItens.setBackground(new Color(204, 153, 255));
        tbItens.getTableHeader().setBackground(new Color(153, 0, 204));
        tbItens.getTableHeader().setForeground(new Color(51, 0, 51));
        tbItens.getTableHeader().setForeground(Color.WHITE);
        Font fonteCabecalho = new Font("Arial", Font.BOLD | Font.ITALIC, 16);
        tbItens.getTableHeader().setFont(fonteCabecalho);

    
        while(!listaVendas.isEmpty()){
            cbxVendas.addItem(listaVendas.get(0));
            listaVendas.remove(0);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVenda = new javax.swing.JLabel();
        cbxVendas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItens = new javax.swing.JTable();
        btGerar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(229, 194, 234));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Relatorio");

        lblVenda.setBackground(new java.awt.Color(231, 210, 243));
        lblVenda.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblVenda.setForeground(new java.awt.Color(51, 0, 51));
        lblVenda.setText("Escolha a venda:");

        cbxVendas.setBackground(new java.awt.Color(251, 243, 252));
        cbxVendas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxVendas.setForeground(new java.awt.Color(51, 0, 51));
        cbxVendas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecionar--" }));
        cbxVendas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 204), null));

        tbItens.setBackground(new java.awt.Color(204, 153, 255));
        tbItens.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        tbItens.setForeground(new java.awt.Color(51, 0, 51));
        tbItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Show", "Quantidade", "Total"
            }
        ));
        tbItens.setSelectionBackground(new java.awt.Color(153, 0, 204));
        tbItens.setSelectionForeground(new java.awt.Color(204, 153, 255));
        jScrollPane1.setViewportView(tbItens);

        btGerar.setBackground(new java.awt.Color(51, 0, 102));
        btGerar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btGerar.setForeground(new java.awt.Color(255, 255, 255));
        btGerar.setText("Gerar");
        btGerar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        btGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/planilha.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btGerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarActionPerformed
       int id = controleVenda.getVendaIdByDescricao(cbxVendas.getSelectedItem().toString());
        PreencherTabela(id);
    }//GEN-LAST:event_btGerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerar;
    private javax.swing.JComboBox<String> cbxVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVenda;
    private javax.swing.JTable tbItens;
    // End of variables declaration//GEN-END:variables
public void PreencherTabela(int id){
    
    listaItens = controleItem.getItensByVenda(id);
    
    tbItens.getColumnModel().getColumn(0).setPreferredWidth(5);
    tbItens.getColumnModel().getColumn(1).setPreferredWidth(80);
    tbItens.getColumnModel().getColumn(2).setPreferredWidth(5);
    tbItens.getColumnModel().getColumn(3).setPreferredWidth(10);

    
    DefaultTableModel modelo = (DefaultTableModel)tbItens.getModel();
    modelo.setNumRows(0);
    for (int i=0 ; i<listaItens.size(); i++){
        int qtd = listaItens.get(i).qtde;
        double valor = controleShow.getValorShowById(listaItens.get(i).id_show);
        double total = qtd*valor;
        modelo.addRow(new Object[]{
        listaItens.get(i).id,
        controleShow.getNomeShowById(listaItens.get(i).id_show),
        qtd,
        total
        });
    }
}
}
